/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('./src/components/room/addForm.vue')['default']
    AddGuestForm: typeof import('./src/components/guest/addGuestForm.vue')['default']
    GuestCard: typeof import('./src/components/GuestCard.vue')['default']
    GuestDropdown: typeof import('./src/components/room/guestDropdown.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainLayout: typeof import('./src/layouts/mainLayout.vue')['default']
    RoomCard: typeof import('./src/components/RoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
